styled the add to cart button and styles parts of the card
Mirio-G/Bakery-Web-App pull request #11
Opened 2024-02-22 14:45 UTC by JohnHo15

2024-02-22 15:07 UTC, JerryNguyen05 requested changes

2024-02-22 15:07 UTC, JerryNguyen05 commented on src/style/card.css
> +
delete blank spaces

2024-02-22 15:07 UTC, JerryNguyen05 commented on src/style/card.css
> +
delete blank spaces

2024-02-26 13:51 UTC, t-t-bui approved these changes

2024-02-26 13:53 UTC, JerryNguyen05 approved these changes

2024-02-26 13:54 UTC, LuisGar2 approved these changes

2024-02-26 13:55 UTC, merged