Making the page for Checkout and Fixing Background Color
Mirio-G/Bakery-Web-App pull request #6
Opened 2024-02-20 15:02 UTC by wowbanhbao

2024-02-20 15:03 UTC, JerryNguyen05 approved these changes

2024-02-20 15:05 UTC, t-t-bui approved these changes
Look good

2024-02-22 13:17 UTC, t-t-bui requested changes
please move checkout into own component(s)

2024-02-22 13:56 UTC, LuisGar2 approved these changes

2024-02-22 14:42 UTC, t-t-bui approved these changes

2024-02-22 14:44 UTC, merged